### ISSUE TITLE
The provider doesn't delete a resource

### ISSUE THREAD

**Issue by jia3apb** [loafoe/terraform-provider-ssh#10]
Hi,

It looks like the provider doesn't delete a file when the resource is deleted by Terraform. Is it expected behavior or my mistake somewhere?

To reproduce:
1. Create an ssh_resource -> a file with some content
2. Apply
2. Delete the resource in the Terraform config
3. Apply

Terraform claims that it deleted the resource but the file is still in place.

**Comment by loafoe** [comment]
@jia3apb the ssh_resource does not track files after creation on the destination, this is by design.
