### ISSUE TITLE
Unable to run command on host

### ISSUE THREAD

**Issue by onedr0p** [loafoe/terraform-provider-ssh#17]
```hcl
terraform {
  required_providers {
    github = {
      source = "integrations/github"
      version = "4.15.1"
    }
    null = {
      source = "hashicorp/null"
      version = "3.1.0"
    }
    ssh = {
      source = "loafoe/ssh"
      version = "0.3.0"
    }
  }
}

data "github_release" "valetudo" {
    repository  = "Valetudo"
    owner       = "Hypfer"
    retrieve_by = "latest"
}

resource "null_resource" "valetudo" {
  provisioner "local-exec" {
    command = "curl -fsSL -o /tmp/valetudo https://github.com/Hypfer/Valetudo/releases/download/${data.github_release.valetudo.release_tag}/valetudo-armv7"
  }
}

resource "ssh_resource" "valetudo" {
  host              = "192.168.1.28"
  user              = "root"
  agent             = true

  file {
    source      = "/tmp/valetudo"
    destination = "/usr/local/bin/valetudo"
    permissions = "0700"
  }

  commands = [
    "/etc/init/S11valetudo restart"
  ]
}
```

This gives a error on run:

```
│ Error: command [/etc/init/S11valetudo restart]: Process exited with status 127
│ 
│   with ssh_resource.valetudo,
│   on main.tf line 30, in resource "ssh_resource" "valetudo":
│   30: resource "ssh_resource" "valetudo" {
```

That error code looks like it cannot find the script...

I can verify the `/etc/init/S11valetudo` script exists on the host:

```
[root@rockrobo ~]# /etc/init/S11valetudo
/etc/init/S11valetudo <start/stop/restart>
[root@rockrobo ~]# ls -la /etc/init/S11valetudo
-rwx------    1 root     root           492 Sep 25 14:38 /etc/init/S11valetudo
```

Also one thing to note if I omit `restart` like

```
  commands = [
    "/etc/init/S11valetudo"
  ]
```

I do not get the error.

I have also tried:

```
  commands = [
    "/bin/sh -c '/etc/init/S11valetudo restart'"
  ]
```

but get the same error too.

**Comment by loafoe** [comment]
There is no explicit dependency between the `null_resource` and the `ssh_resource` so there is a good chance Terraform will try to execute both creates in parallel causing a race condition on the source. You should add a `depnds_on` to ensure the null_resource has finished copying the file.

**Comment by onedr0p** [comment]
I am still running into the same error, that's not it.

```bash
resource "null_resource" "valetudo" {
  provisioner "local-exec" {
    command = "curl -fsSL -o /tmp/valetudo https://github.com/Hypfer/Valetudo/releases/download/${data.github_release.valetudo.release_tag}/valetudo-armv7"
  }
}

resource "ssh_resource" "valetudo" {
  host              = "192.168.1.28"
  user              = "root"
  agent             = true

  file {
    source      = "/tmp/valetudo"
    destination = "/usr/local/bin/valetudo"
    permissions = "0700"
  }

  commands = [
    "/etc/init/S11valetudo restart"
  ]

  depends_on = [
    null_resource.valetudo
  ]
}
```

Output:

```
 Error: command [/etc/init/S11valetudo restart]: Process exited with status 127
│ 
│   with ssh_resource.valetudo,
│   on valetudo.tf line 13, in resource "ssh_resource" "valetudo":
│   13: resource "ssh_resource" "valetudo" {
```

**Comment by onedr0p** [comment]
As I mentioned the command runs fine if I omit `restart` on the args. But that is kind of what I need to do :/

**Comment by loafoe** [comment]
There is a `debug_log` option available:

```hcl
provider "ssh" {
   debug_log = "/tmp/ssh.log"
}
```

This should capture stderr and stdout of the remote command. Can you try this? Hopefully it provides some more details.

**Comment by onedr0p** [comment]
The only thing I see in the log is:

```
✖ cat /tmp/ssh.log
Copied /tmp/valetudo to remote file 192.168.1.28:/usr/local/bin/valetudo: 31676240 bytes
Permissions file /usr/local/bin/valetudo:0700:
```

**Comment by loafoe** [comment]
Ok, that is good. the binary is copied and given the correct permission. The next thing I would do is to examine the content of this `/etc/init/S11valetudo` script that is apparantly already on the target machine e.g. what happens if you manually run `/etc/init/S11valetudo restart` ? Do you also get the `exit 127` error?

**Comment by onedr0p** [comment]
The command runs fine...

```
[root@rockrobo ~]# /etc/init/S11valetudo restart
stopping valetudo
starting valetudo
[root@rockrobo ~]# echo $?
1
```

**Comment by loafoe** [comment]
That looks like a non-zero exit code (`1`). I'll need to check if the resource treats that as a success or not. In the meantime is it possible to coerce the script to return `0` on success?

**Comment by onedr0p** [comment]
I can attempt to correct that but error 127 likely means the script isn't found, right?

**Comment by loafoe** [comment]
Yeah, `127` is usually an indication of missing file or library.  Can you add an `ls -l /etc/init/S11valetudo` at the start of the commands array? This should have it show up in the debug log.

**Comment by loafoe** [comment]
@onedr0p released `v0.4.0` which adds improved debugging e.g. it prints the stdout and stderr of the command in case of error. This might provide more insights in the issue you are having. More importantly, the resource also errors out when a file fails to copy correctly to the host. This was ignored before.

**Comment by onedr0p** [comment]
Woah, thanks for the update, we are getting somewhere, here are the new logs:

```
❯ cat /tmp/ssh.log
Copied /tmp/valetudo to remote file 192.168.1.28:/usr/local/bin/valetudo: 31676240 bytes
Permissions file /usr/local/bin/valetudo:0700:
command: /etc/init/S11valetudo restart
done: true
stdout:
stopping valetudo
starting valetudo

stderr:
/etc/init/S11valetudo: line 29: start-stop-daemon: not found
/etc/init/S11valetudo: line 29: start-stop-daemon: not found

error: Process exited with status 127
```

It appears the command is run but like you said there's an error in the script. However I do not see that stderr in the console when I run the command on `192.168.1.28`.

**Comment by onedr0p** [comment]
I would say if I didn't want to debug the script (outside the context of this issue anyways), a good workaround is to

```
  commands = [
    "/etc/init/S11valetudo restart || true"
  ]
```

**Comment by loafoe** [comment]
Ah, nice, good we're seeing some more details now.

So one thing I can think of is that the environment (`PATH`, etc) is not the identical between your login session and the ssh shell. You could add a `set` to compare it, or wrap the command in a login shell maybe. Adding `|| true` just makes the provider happy but might hide a crucial failure i.e. the service may not have restarted at all

**Comment by onedr0p** [comment]
Definitely, I updated the script to be the absolute path to `start-stop-daemon` and now I'm getting the correct error code of 1 returned when I run with Terraform.

**Comment by loafoe** [comment]
Improved the debug-ability for sure, thank you!
