### ISSUE TITLE
Make timeout configurable

### ISSUE THREAD

**Issue by innovate-invent** [loafoe/terraform-provider-ssh#24]
My ssh commands can take over 30min to succeed
https://github.com/loafoe/terraform-provider-ssh/blob/dc216fd420641c55fec1546e709501bb95fb0367/ssh/resource_resource.go#L284

**Comment by loafoe** [comment]
Thanks for the request, makes perfect sense, will implement

**Comment by loafoe** [comment]
@innovate-invent available in `v1.1.0` of the provider
