### ISSUE TITLE
redhat7.x

### ISSUE THREAD

**Issue by mackill54** [loafoe/terraform-provider-ssh#33]
Erorr with RedHat 7.x

return error
copying files to remote: Process exited with status 141

with Redhat 8.x everything is ok

**Comment by arbourd** [comment]
Sounds like something with the SSH agent, and not this provider.

**Comment by mackill54** [comment]
No, problem was enabled tlog on rhel 7.x, the same configuration with tlog for rhel 8.x is ok

**Comment by tuxpeople** [comment]
Could also be a permission error... I had such errors as well. Try this:

1. Login with the same user to the RHEL7 machine
2. use `touch` to create a file as this user with the same path and filename as the provider would do

Check the error.

**Comment by loafoe** [comment]
@mackill54 if this is still relevant, can you please try it with version `2.3.0` and debugging enabled? This should get us some more details, thx!

**Comment by mackill54** [comment]
I will try new version, thx!
