### ISSUE TITLE
Destroy `ssh_resource`

### ISSUE THREAD

**Issue by arbourd** [loafoe/terraform-provider-ssh#37]
First off, this is an awesome idea that really solves a lot of the problems of provisioners by not using them.

Would you consider a `ssh_destroy_resource`, which only runs the SSH script on destroy, rather than create/update?

The value of it would be getting around `when = destroy` provisioners as there are numerous bugs with them (see: https://github.com/hashicorp/terraform/issues/13549, https://github.com/hashicorp/terraform/issues/31266).

I would be happy to contribute this.

**Comment by loafoe** [comment]
@arbourd definitely would accept such a resource!

**Comment by loafoe** [comment]
@arbourd `v2.0.0` is now available with this feature. Thanks for suggesting / helping with this!
