### ISSUE TITLE
Validate configuration `when = "destroy"`

### ISSUE THREAD

**Issue by arbourd** [loafoe/terraform-provider-ssh#40]
The configuration of the object is validated (or asserted) with the normal create flow. But, if using `when = "destroy"` you wouldn't experience the errors when the objected in state is initially created, but you will when trying to destroy them.

For example:

```
╷
│ Error: privateKey must be set when 'commands' is specified and 'agent' is false
│
│
╵
```

Perhaps some validation that isn't `ssh` runtime dependent should be moved into its own function that can be called for every create and destroy?

**Comment by loafoe** [comment]
Thanks @arbourd , this should be addressed in `v2.0.1` , please give it a go
