### ISSUE TITLE
One ressource, two different `when`

### ISSUE THREAD

**Issue by tuxpeople** [loafoe/terraform-provider-ssh#53]
I tried to understand from the documentation how to archive this, but I failed:

I'd like to create a `ssh_resource` which creates a file and run some commands. But when destroying that `ssh_resource` I'd like to delete the file and run other commands. 

Let's assume I use this resource:

```
resource "ssh_resource" "touch_file" {
  when = "create"

  host         = var.host
  user         = var.user
  private_key = var.ssh_key

  file {
    content     = "touch /opt/file"
    destination = "/tmp/hello.sh"
    permissions = "0700"
  }

  commands = [
    "/tmp/hello.sh"
  ]
}
```

How would I add a `when = destroy` to delete the file `/tmp/hello.sh` and to run the command `delete /opt/file`?

**Comment by loafoe** [comment]
@tuxpeople you would create a second resource:

```hcl
resource "ssh_resource" "destroy_file" {
  when = "destroy"

  host         = var.host
  user         = var.user
  private_key = var.ssh_key

  commands = [
    "rm /opt/file"
  ]
}
```

This second resource will be a NOOP when you `apply` but will kick into action on `destroy`

**Comment by tuxpeople** [comment]
Ok, got it. So I basically need to create two resources for the same thing. Thanks for the fast feedback!

I assume an enhancement request for nested blocks is a bad idea as it would be a breaking change, right?

**Comment by loafoe** [comment]
Yeah, I would prefer to keep the resource simple and flat 😃

**Comment by tuxpeople** [comment]
One more question: The second ressource only helps when using `terraform destroy`, right? Is there a way to use destroy commands when using `terraform taint` on the original ressource?

**Comment by loafoe** [comment]
You can solve the `taint` flow by creating an explicit dependency (if none exists) on the `touch_file` resource from the `destroy_file`:

```hcl
resource "ssh_resource" "destroy_file" {
  when = "destroy"
  ...

  depends_on = [ssh_resource.touch_file]
}
```

Now if you `terraform taint ssh_resource.touch_file` it will get destroyed and recreated, but that will also trigger the same lifecyle for the `destroy_file` resource, achieving what you want I think

**Comment by tuxpeople** [comment]
I think I understand. Thanks a lot @loafoe!
