### ISSUE TITLE
How to connect using a password instead of a private key?

### ISSUE THREAD

**Issue by jalemann** [loafoe/terraform-provider-ssh#59]
I am trying to solve a university exercise where I have to use Terraform to execute remote commands and this provider seems pretty intuitive to use.
However to connect via ssh I only have a user and password and there is no way for me to setup keys for authentication.

I tried to put the password as a `pre_command` but that didn't work.

Is there a way one can use a password instead of a private key?

**Comment by loafoe** [comment]
hi @jalemann, password support is not implemented yet. The underlying `easyssh` library does seem to support password based authentication. It should be fairly straightforward to add support for this. Will accept a PR for this, otherwise will look add implementing this post the holidays 👍🏻

**Comment by jalemann** [comment]
Thanks for the fast reply, maybe I can manage to implement it and open a PR.

Anyway, enjoy the holidays!

**Comment by jalemann** [comment]
I opened a PR #60 

Maybe you can have a look at it after the holidays. This was my first time seeing Go code and I didn't test it as I didn't want to publish it and didn't know how else to test.
Still it seemed quite straight forward so I thought I'd give it a shot and you can double check whenever you have time.

**Comment by loafoe** [comment]
@jalemann implemented in `v2.4.0`
