### ISSUE TITLE
How to connect when private key has a passphrase?

### ISSUE THREAD

**Issue by mrsimonemms** [loafoe/terraform-provider-ssh#61]
I've been trying to connect to a VM which has an SSH key which is secured with a passphrase.

I can't see a way of achieving that with the current setup, so I'd suggest allowing a `passphrase` argument to the Terraform resources?

If I investigate and raised a PR, is that something that would be helpful?

**Comment by loafoe** [comment]
@mrsimonemms will definitely accept a `PR` that will support passhprase protected private keys!

**Comment by mrsimonemms** [comment]
@loafoe great stuff. It won't be next week (holiday), but I'll have a look around

**Comment by loafoe** [comment]
@mrsimonemms we needed this feature this week so I went ahead and added support. The implementation is such that the `passphrase` will only be read from an environment. This prevents both the private key and the passphrase from ending up in Terraform, defeating the passphrase. This might not be as convenient as making it a argument in the resource, but I believe this a more secure implementation as it ensures the key and passphrase are not stored side by side. 

Please try it out in `v2.5.0`

**Comment by mrsimonemms** [comment]
Hey @loafoe, good work.

It's a difficult question from a philosophical point of view. You're absolutely correct that it probably doesn't want to be in the Terraform state, but it's not really with the Terraform idiom to read from envvars rather than variables. What you've done absolutely meets my needs, so I'm very happy - thank you for doing this.
