### ISSUE TITLE
how to run conditionally?

### ISSUE THREAD

**Issue by chris-aeviator** [loafoe/terraform-provider-ssh#72]
I'm looking into a way to trigger a file copy only after a parameter evaluates to true (e.g. count > 0), since I'm setting the host IP only after executing a prev command. Is it somehow possible to use this provider  conditionally with a logical expression?

**Comment by loafoe** [comment]
@chris-aeviator you may need to split your Terraform in multiple runs if the IP is only known under certain conditions i.e. kick off the ssh workflow only once that condition is met and read the IP using something like remote state.

**Comment by chris-aeviator** [comment]
I'm using terraform cloud sync here, if I understand you correctly I'd need to have a variable for every element in count that holds the IP?

**Comment by loafoe** [comment]
@chris-aeviator in case you need values (e.g. IP address) then `for_each` might be better approach. Do keep in mind that the keys should be known during the planning phase.

**Comment by loafoe** [comment]
closing for now
